import { Metadata } from 'next';
import './global.css';
import { ApolloProvider } from './provider/ApolloProvider';
import { DashBoard } from './components/DashBoard';

export const metadata: Metadata = {
  title: 'Welcome to todo-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DashBoard />
        <ApolloProvider>{children}</ApolloProvider>
      </body>
    </html>
  );
}
